# Generated by Django 3.2.25 on 2024-10-05 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Range',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('min_amount', models.DecimalField(decimal_places=2, help_text='Cantidad mínima del rango', max_digits=20)),
                ('max_amount', models.DecimalField(decimal_places=2, help_text='Cantidad máxima del rango', max_digits=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='', max_length=250, null=True)),
            ],
            options={
                'unique_together': {('min_amount', 'max_amount')},
            },
        ),
        migrations.AddField(
            model_name='commission',
            name='range',
            field=models.ForeignKey(default=None, help_text='Rango de cantidad asociado a esta comisión', on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='coin.range'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='commission',
            unique_together={('base_currency', 'target_currency', 'range')},
        ),
    ]
